### ISSUE TITLE
Why block using a bucket on a cauldron?

### ISSUE THREAD

**Issue by sargunv** [CottonMC/cotton#17]
Why does Cotton disable vanilla's ability to empty a cauldron with a bucket? Seems like cauldron behaviors would work fine without explicitly blocking that feature (for example, cotton doesn't block doing the same with bottles). I'm hesitant to ship a mod depending on a library that changes vanilla functionality on its own.

https://github.com/CottonMC/cotton/blob/b024f6415f318db02907a6f3e603cc92de8840cb/src/main/java/io/github/cottonmc/cotton/mixins/MixinCauldronBehavior.java#L34-L38

**Comment by Boundarybreaker** [comment]
Ah, that's an artifact from when we used to make it implement the fluid pickup stuff. I'll remove it quick.

**Comment by sargunv** [comment]
Thanks!

**Comment by Boundarybreaker** [comment]
New Artifactory version now no longer has this.
