### ISSUE TITLE
Build 0.6.9+1.14.2: Crash on World Creation, Server Join. With or without other mods.

### ISSUE THREAD

**Issue by el0c** [CottonMC/cotton#24]
Saw the recent 0.6.9.1.14.2 build and snagged it for my mod pack. Tested on both a multiplayer server and single player, as well as with mods and with out. 
This is with Fabric loader 1.14.2+build.2 and Fabric API 0.3.0 build 169.

With (a lot of) mods log:
https://pastebin.com/xeXeyJz1
Without mods log (besides Fabric API dependency):
https://pastebin.com/e7FPCj6K

Hope this helps, let me know if there's any other logs I could produce that may do so.

EDIT: I should add that the crash with mods was tested on both MP and SP but the test without mods was only performed in SP.

**Comment by Boundarybreaker** [comment]
Ah, for some reason profiling is enabled when it shouldn't be, leading to an NPE. I guess the easiest thing to do here would be to just get rid of the profiling option for now.

**Comment by Boundarybreaker** [comment]
I'm gonna keep this open for the sake of trying to source the actual problem at hand, but I'm uploading a hotfix version now.
