### ISSUE TITLE
crash with cotton 1.14.3 pre 2

### ISSUE THREAD

**Issue by Nathan22211** [CottonMC/Cotton#27]
it happens just before loading a world https://pastebin.com/cagcYHTz

**Comment by falseresync** [comment]
Cotton doesn’t yet support this version of Minecraft.

**Comment by Boundarybreaker** [comment]
This is a yarns issue, so it's luckily an easy fix, but we're going to only target non-snapshot versions of 1.14.x from here on out.

**Comment by Juuxel** [comment]
This should be fixed now (in 720e021).
