### ISSUE TITLE
Let's talk: Multi Project setup

### ISSUE THREAD

**Issue by Ansraer** [CottonMC/Cotton#3]
I think that before everyone goes crazy and starts to add stuff to this project we should set down some basic guidelines for where to put what.

- [ ] Cotton (cotton) itself is the main module, all our sub modules depend on it. It is a library containing utility stuff like config loading or logger classes. In general everything that is needed by other projects goes here.

- [ ] More resources (cotton-resources): is where we will add more resources that other mods need. Ingots, ore, maybe even a few simple parts.

- [ ] Energy API (cotton-energy). This is where our api goes. So everything cable/tube/wire related and maybe some tools to build them. I suggest we further split it into two projects, the API and a basic implementation. (See my comment on the energy issue)

- [ ] Cotton tweaks (cotton-tweaks) fixes and additions to vanilla. I am not really sure how much we want to tweak vanilla, it should be up to actual mods to do it instead.

Any thoughts?

**Comment by Pannoniae** [comment]
And don't forget tweaks module, which is for fixes/additions for vanilla. Like fixing dispensers so they can plant seeds (automated farm)

**Comment by Jacky2611** [comment]
Not sure if it wouldn't make more sense to have a planter block or something like that. But I added the tweaks module

**Comment by Pannoniae** [comment]
See #5

**Comment by Frontrider** [comment]
split tweaks, into a feature, and a bugfix module, if we really do "bugfixes".

**Comment by falkreon** [comment]
We have a wiki here in this project. Anyone want to make a contributor hub and direct people to satellite projects for appropriate functionality?

**Comment by falkreon** [comment]
The Splittening is complete!
