### ISSUE TITLE
1.14.4 crash on load (io/github/cottonmc/cotton/gui/CottonScreenController)

### ISSUE THREAD

**Issue by SDUBZ** [CottonMC/Cotton#34]
fabric:1.14.4
cotton etc : 
cotton: Cotton 1.0.0-rc.2
		cotton-cauldron: Cotton Cauldron 1.0.0-rc.1
		cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
		cotton-commons: Cotton Commons 1.0.0-rc.1
		cotton-config: Cotton Config 1.0.0-rc.1
		cotton-datapack: Cotton Datapack 1.0.0-rc.1
		cotton-energy: Cotton Energy 1.5.0+1.14.3
		cotton-logging: Cotton Logging 1.0.0-rc.1
		cotton-player-events: Cotton Player Events 1.0.0-rc.2
		cotton-resources: Cotton Resources 1.3.2+1.14.3
libcd: LibCapableData 1.3.0+1.14.3
fabric: Fabric API 0.3.0+build.200

crash report:
[crash-2019-07-21_16.09.27-client.txt](https://github.com/CottonMC/Cotton/files/3414345/crash-2019-07-21_16.09.27-client.txt)
log: 
[latest.log](https://github.com/CottonMC/Cotton/files/3414349/latest.log)

**Comment by Boundarybreaker** [comment]
LibGui is needed; it contains all this code now. The packages are the same, so just drop that in.

**Comment by SDUBZ** [comment]
okay thank you :)
also why isnt it listed as dependency then

**Comment by Boundarybreaker** [comment]
It isn't one for Cotton. Whichever mod is causing this (I'm betting VivaTech) hasn't been updated for the new Cotton rework, so it doesn't realize the code's been moved elsewhere.
