### ISSUE TITLE
Duplicate Mod ID's of ModMenu

### ISSUE THREAD

**Issue by sylv256** [CottonMC/cotton#41]
**Describe the bug**
Hi! I have recently been experiencing an issue where there are two mods which have duplicate mod ids (specifically the id "modmenu"). When I remove one of them, I get a warning telling me that 2 other mods depend on that mod. These mods came with either Cotton or Cotton Resources. Those are the only mods that I have installed besides Fabric API.

**To Reproduce**
1. Install latest version of Fabric, Fabric API, Loom, Cotton
2. Build and Run
3. See error

**Expected behavior**
There shouldn't be two mods with the same id ("modmenu") and there also shouldn't be two mods depending on both ModMenu mods.

**Screenshot**
<img width="1215" alt="Screen Shot 2020-06-03 at 4 42 15 AM" src="https://user-images.githubusercontent.com/18603248/83615544-b32b0b80-a554-11ea-9929-1083fcfd9a59.png">

**Versions:**
 - Cotton | 1.0.3
 - Cotton Resources | 1.5.1+1.15.2
 - io.github.prospector.modmenu:ModMenu | 1.6.3-94
 - io.github.prospector:modmenu | 1.8.4
 - Fabric API | 0.11.1+build.312-1.15
 - Fabric Loader | 0.8.5+build.199
 - Yarn Mappings | 1.15.2+build.17
 - Fabric Loom | 0.2.7-SNAPSHOT
 - Minecraft | 1.15.2

**Additional context**
Before anyone asks, I have installed the latest version of the following libraries/mods:
 - Fabric API
 - Fabric Loader
 - Fabric Loom
 - Cotton
 - Cotton Resources
 - Yarn Mappings

I do not have any other mods except those listed above as well as their dependencies.
I have Java 11 installed and I am running Mac OS X 10.13.6 (High Sierra).

**Comment by LemmaEOF** [comment]
looks like it's [because of Cotton](https://github.com/CottonMC/Cotton/blob/1.15/build.gradle#L53), which is weird and frustrating, because cotton doesn't *do* anything with modmenu and I don't remember adding that. I'll remove it soon.

**Comment by sylv256** [comment]
#42
