### ISSUE TITLE
Probably my fault

### ISSUE THREAD

**Issue by DanShu15** [CottonMC/cotton#44]
Just some error message spam, no crash or client side disconnects tho. Not really sure who on the server or what caused it.

Console snippet:
https://pastebin.com/aqMNk5wS
 I can get a full log next time it happens if needed, my current log is absolutely massive so I've cleared it and I'll restart in a couple hours or when everyone logs off

**To Reproduce**
\o/ beats me but I did uninstall the Tiered mod with this last update earlier today, other than that all I've done is added some recipes with data packs for the compost recipes mod and to make Tech Reborn rubies tradeable for Azuma rubies

**Version of the (please complete the following information):**
 - Cotton 1.0.3
 - Jankson Fabric 2.0.1+j1.2.0 jar in jar
 - LibCD 2.4.1 for 1.15.2
 - Fabric API 0.11.1 build 312-1.15
 - Minecraft 1.15.2

**Additional context** *Optional*

**Comment by LemmaEOF** [comment]
Hm, this looks to be a LibGui issue. Tiered likely uses it for rendering guis, and includes it inside the jar.

**Comment by DanShu15** [comment]
sweet, I've got an entity error that I believe is from removing Tiered as well, so even tho it won't work properly, adding it back in should fix it :)
Thank you very much Boundary!
