### ISSUE TITLE
CTD on world load 1.16

### ISSUE THREAD

**Issue by DNewman5** [CottonMC/cotton#45]
org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for accessor mixin io.github.cottonmc.cotton.datapack.mixins.ResourcePackManagerAccessor. The mixin is missing from mixins.cotton-datapack.json which owns package io.github.cottonmc.cotton.datapack.mixins.* and the mixin has not been applied.
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.5)

**Comment by LemmaEOF** [comment]
oh god damnit

**Comment by LemmaEOF** [comment]
Fixed in 1.0.5
