### ISSUE TITLE
Crashes When Creating New World

### ISSUE THREAD

**Issue by queenielawrens** [CottonMC/cotton#46]
### **Fixed in 1.0.5**

**Describe the bug**
Crashes when trying to create new world. Not sure it's caused by Cotton, but when cotton was removed it worked properly. I have retried and it happens the same way each time. Also can not open worlds created without mod.

**To Reproduce**
1. Launch Client
2. Create new singleplayer world (mine was cheats on & survival with many other mods and datapacks though I don't know if these are necessary) 
3. See error

**Expected behavior**
Create new world and open.

**Version of the (please complete the following information):**
 - Cotton 1.0.4
 - Fabric API 0.14.0+build.371-1.16
 - Minecraft 1.16.1

**Additional context** *Optional*
Crashlog from creating new world:
https://pastebin.com/qaNhCddp

**Comment by LemmaEOF** [comment]
Fixed in Cotton 1.0.5, please update

**Comment by queenielawrens** [comment]
fixed in 1.0.5
