### ISSUE TITLE
Global Datapacks are disabled by default.

### ISSUE THREAD

**Issue by YTG1234** [CottonMC/cotton#47]
**Describe the bug**
When creating a world, I need to manually enable the global datapacks (using commands, they are not in the GUI).

**To Reproduce**
1. Create a World
1. Run /datapack list
1. See the global datapacks are disabled.

**Expected behavior** *Optional*
All global datapacks should be enabled.

**Version of the (please complete the following information):**
 - Mod: 1.0.5
 - Fabric API: 0.13.1+build.370-1.16
 - Minecraft: 1.16.1

**Comment by LemmaEOF** [comment]
oh god, they're not even in the gui? I realized this would be a problem but didn't have time to actually fix it today. I'll get it done ASAP!

**Comment by YTG1234** [comment]
@Boundarybreaker Any status update?

**Comment by LemmaEOF** [comment]
Been quite busy these past few days.

**Comment by LemmaEOF** [comment]
I can fix this in code but not sure if I can publish atm
