### ISSUE TITLE
Let's Talk: Tweaks, Vanilla+

### ISSUE THREAD

**Issue by Pannoniae** [CottonMC/cotton#5]
The idea is to have a tweaks module to fix long-standing pains with vanilla. (dispenser plant seeds, proper stair math, etc...)
/discuss

**Comment by Frontrider** [comment]
this is 2 mods: 
fixes (bugfixes)
tweaks (dispenser planting seeds, etc)

**Comment by falkreon** [comment]
closing out old issues - further discussion can happen on the cotton-tweaks issue tracker :)
