### ISSUE TITLE
crash with 1.16.2

### ISSUE THREAD

**Issue by Nathan22211** [CottonMC/cotton#50]
**Describe the bug**
game crashes on startup with exit code -1

**To Reproduce**
1.  launch the game with cotton and fabric API in the mods folder
2. it should crash

**Expected behavior** *Optional*
should launch without issue

**Screenshots** *Optional*

**Version of the (please complete the following information):**
 - Cotton 1.0.7
 - Fabric API 0.9.2+build.206
 - Minecraft 1.16.2

**Additional context** *Optional*
here's a crash log, it mentions cotton cauldron and libCD in it. If it's set to secret by mistake just inform me https://gist.github.com/Nathan22211/7ed916b7f5cc0441d69c015c3e11ea4f

**Comment by LemmaEOF** [comment]
Cotton needs to be converted over to LibDP. I'll do that when I have time.

**Comment by magneticflux-** [comment]
As a quick workaround, you can manually upgrade the Jankson dependency and keep the older version of LibCD so the `cauldron` module still loads properly.
I used this snippet:
```gradle
dependencies {
    // ...

    modImplementation 'io.github.cottonmc.cotton:cotton:1.0.7'
    include 'io.github.cottonmc.cotton:cotton:1.0.7'

    modImplementation 'io.github.cottonmc:Jankson-Fabric:3.0.1+j1.2.0'
    include 'io.github.cottonmc:Jankson-Fabric:3.0.1+j1.2.0'

    // ...
}
```
