### ISSUE TITLE
Dependency on Jankson causes crashes if Jankson is not added to classpath outside of a dev env

### ISSUE THREAD

**Issue by Boundarybreaker** [CottonMC/cotton#6]
I've been working on getting Cotton-Resources up and running, and I've run into the issue that Jankson isn't getting added to the classpath outside of Cotton's dev environment. I've tried shadowing, but that doesn't seem to have worked. I'm not very good with Gradle, so if someone else has an idea of how to help, let me know!

**Comment by Boundarybreaker** [comment]
(note: I discovered this by trying to run cotton-resources with cotton as a modCompile dependency)

**Comment by falkreon** [comment]
Fixed by 290a5b6
