### ISSUE TITLE
Let's Talk: Cotton-resources and its usage

### ISSUE THREAD

**Issue by Pannoniae** [CottonMC/cotton#9]
Let's face it: some guys on Discord raised the (very valid) concern that cotton-resources is going to get ignored, and mods will register ores and their stuff themselves.
My idea would be to simply merge that functionality to core, so modders can rely on it being present, so they won't have ores registered.

**Comment by Jacky2611** [comment]
We can merge separate projects into one using gradle. At least during development, I would like to keep the projects separate.

**Comment by Frontrider** [comment]
If we have the projects, I can set it up.

**Comment by falkreon** [comment]
I think the consensus has been that the projects will stay separate while we're in development, and as we release mods we can absolutely reevaluate merging projects. At that time, let's talk about it on the cotton-resources issue tracker :)
